# Generated by Django 2.2.6 on 2019-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('nacionalidade', models.CharField(max_length=40, verbose_name='nacionalidade')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf')),
                ('telefone', models.CharField(default='', editable=False, max_length=15, verbose_name='celular')),
                ('data_nascimento', models.DateField(null=True, verbose_name='data_nascimento')),
                ('genero', models.CharField(max_length=15, null=True, verbose_name='genero')),
                ('estado_civil', models.CharField(max_length=15, null=True, verbose_name='estado_civil')),
                ('deficiencia', models.CharField(max_length=5, null=True, verbose_name='deficiencia')),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='cep')),
                ('logradouro', models.CharField(max_length=40, null=True, verbose_name='rua')),
                ('numero', models.IntegerField(null=True, verbose_name='numero')),
                ('complemento', models.CharField(max_length=60, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='bairro')),
                ('estado', models.CharField(max_length=4, null=True, verbose_name='estados')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='idades')),
                ('matricula', models.CharField(max_length=20, null=True)),
                ('curso', models.CharField(max_length=30, null=True, verbose_name='curso')),
                ('periodo', models.CharField(blank=True, max_length=5, null=True, verbose_name='periodo')),
                ('arquivo', models.FileField(null=True, upload_to='arquivos')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='nome')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
