# Generated by Django 2.2.6 on 2019-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='deficiencia',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tipo_deficiencia',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
        migrations.AddField(
            model_name='candidato',
            name='desc_curso',
            field=models.CharField(max_length=60, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='contato',
            name='assunto',
            field=models.CharField(max_length=60, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='contato',
            name='desc_empresa',
            field=models.CharField(max_length=60, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(max_length=60, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(max_length=3, null=True, verbose_name='Peridodo'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=60, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome'),
        ),
    ]
